apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://monitoring-prometheus-production.up.railway.app
    isDefault: true
    editable: false
    jsonData:
      tlsSkipVerify: true